### ISSUE TITLE
1.20 Fabric?

### ISSUE THREAD

**Issue by Soniflare** [elmfrain/parkourhelper#8]
Is there a way to make a version for Fabric on Minecraft 1.20?

**Comment by mattmoparkour** [comment]
Yeah, are there any plans for later versions or even a port to fabric?

**Comment by elmfrain** [comment]
Yeah, sorry for not updating this mod in a while, I've been busy with work and school.

Since there is interest for this mod to be updated, I do have plans to update this mod for later versions.

On top of that, I do plan to port this mod into Fabric because I see that mod users are using Fabric more than ever (including me), so I think it would benefit the users and the mod for a port to be made.

**Comment by elmfer** [comment]
Fabric port of this mod for Minecraft 1.20.4 is under way!

[MC1.20.4 Fabric Branch](https://github.com/elmfrain/parkour_recorder/tree/fabric-1.20.X)

**Comment by mattmoparkour** [comment]
Love you guys

**Comment by elmfrain** [comment]
I am happy to announce that this mod is now officially available for Minecraft Fabric 1.20.4! You may download it from:
* [CurseForge](https://www.curseforge.com/minecraft/mc-mods/parkour-recorder)
* [Modrinth](https://modrinth.com/mod/prmod)
* [GitHub](https://github.com/elmfrain/parkour_recorder/releases/tag/1.1.2.1-1.20.4)
